### ISSUE TITLE
Logo not loading

### ISSUE THREAD

**Issue by DanilaVladi** [VWAS/vwas.github.io#7]
Loading the Codinator logo fails... (Error 404 Not found)

**Comment by enociz** [comment]
Seems like a common problem - will look into it when I get time

**Comment by DanilaVladi** [comment]
Any status updates?

**Comment by enociz** [comment]
No updates as of yet. I've seen the problem in other similar sites. I need some time

**Comment by DanilaVladi** [comment]
Ok, maybe we just load the logos directly from the AppStore with the iTunes API or move the logos to this repository as a temporary solution?  That would also be something I could hand you off...

**Comment by DanilaVladi** [comment]
I've fixed the logo for now... The solution is ugly enough for now

**Comment by enociz** [comment]
Got it
